properties
BitMask-Technologies/xbox-tokyo-audacia-api pull request #17
Opened 2021-11-03 17:30 UTC by BrainiacRawkib

2021-11-04 06:48 UTC, DeeMATT requested changes

2021-11-04 06:48 UTC, DeeMATT commented on properties/filters.py
> +    min_garage = filters.NumberFilter(field_name="bathrooms", lookup_expr='gte')
field_name="bathrooms"

That seems like a mistake

2021-11-04 06:48 UTC, DeeMATT commented on properties/models.py
> +    state = models.CharField(max_length=25, choices=STATE_CHOICES, default='lagos')
Why pass a default and it was "lagos"?

2021-11-04 06:48 UTC, DeeMATT commented on properties/models.py
> +    state = models.CharField(max_length=25, choices=STATE_CHOICES, default='lagos')
TextField is better

2021-11-04 06:48 UTC, DeeMATT commented on properties/views.py
> +class PropertyListView(generics.ListAPIView):
Why didn't you follow the pattern from the existing APIs. We can't have some classes running using a different kinda CBV and others running with another.

2021-11-04 06:48 UTC, DeeMATT commented on properties/views.py
> +    def get(self, request, *args, **kwargs):
Still not a complete job. U only sent for GET

2021-11-04 06:48 UTC, DeeMATT commented
Please let's meet this AM

2021-11-04 06:58 UTC, DeeMATT requested changes

2021-11-04 06:58 UTC, DeeMATT commented on properties/utils.py
> +STATE_CHOICES = (
Why state choices ?

2021-11-04 11:12 UTC, BrainiacRawkib commented on properties/filters.py
> +    min_garage = filters.NumberFilter(field_name="bathrooms", lookup_expr='gte')
That's true.

2021-11-04 11:15 UTC, BrainiacRawkib commented on properties/models.py
> +    state = models.CharField(max_length=25, choices=STATE_CHOICES, default='lagos')
Default to lagos because it is going to be a choice field in the front-end. We can always change the default to something else later.

2021-11-04 11:23 UTC, BrainiacRawkib commented on properties/views.py
> +class PropertyListView(generics.ListAPIView):
Ok I will change that ASAP.

2021-11-04 11:24 UTC, BrainiacRawkib commented on properties/views.py
> +    def get(self, request, *args, **kwargs):
I will push a complete job soon, I trying to resolve some issues with the filters.

2021-11-04 11:26 UTC, BrainiacRawkib commented on properties/utils.py
> +STATE_CHOICES = (
I thought it would be nice, incase the properties isn't in just one state.

2021-11-08 07:13 UTC, DeeMATT commented
@BrainiacRawkib The code didn't pass check

2021-11-09 20:39 UTC, DeeMATT requested changes
Awesome. I enjoyed reviewing your code. Thumbs up

2021-11-09 20:39 UTC, DeeMATT commented on properties/utils.py
> +def delete_property(id):
Lovely but you didn't use it in the HTTP DELETE request for property but this was suppose to accept an instance of the Property model class so there'll be no need to do 

property_ = Property.objects.get(id=id)

knowing very well that the id passed as argument was captured from an already existing instance of Property model

2021-11-09 20:39 UTC, DeeMATT commented on properties/utils.py
> +def delete_property(id):
Reference my delete_realtor()

2021-11-09 20:39 UTC, DeeMATT commented on properties/serializers.py
> +            property = Property.objects.create(
Why not just call

 : create_property() from utils.py file : 

to avoid repetition of similar code

2021-11-09 20:39 UTC, DeeMATT commented on properties/utils.py
> +        for property in properties[:70]:
This seems like the value for 70 was hardcoded. We might need to handle it a different way to avoid touching code everytime it needs to be adjusted in future and also for better control

2021-11-09 20:39 UTC, DeeMATT commented on properties/utils.py
> +def get_recent_properties(properties, days_span):
We will need to re-write this function so that it can meet business requirements because the algorithm you currently used is slightly different from what is expected

2021-11-09 20:39 UTC, DeeMATT commented on properties/utils.py
> +def get_archived_properties(properties):
Where is the properties coming from ?

2021-11-09 20:39 UTC, DeeMATT commented on properties/utils.py
> +def get_archived_properties(properties):
The DB query that returned the list of properties should be executed inside this function

2021-11-09 20:39 UTC, DeeMATT commented on properties/utils.py
> +def get_archived_properties(properties):
Properties.objects.filter(is_archive=True)

2021-11-10 13:41 UTC, BrainiacRawkib commented on properties/views.py
> +                property_to_delete.available = False
I think there will be need for adding a creator field that reference a User

2021-11-10 13:43 UTC, BrainiacRawkib commented on properties/views.py
> +            if user.is_active or user is not None:
I think there will be need for adding a creator field that reference a User

2021-11-12 12:18 UTC, DeeMATT approved these changes
Thanks

2021-11-12 12:58 UTC, merged